[package]
name = "sync-adapter-ffi"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]

[lib]
name = "sync_adapter"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
serde = "1.0"
serde_json = "1.0"
error-chain = "0.11"

[dependencies.sync15-adapter]
path = "../"

